// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('pouet', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('pouet', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 554, height: 699 })
    await driver.findElement(By.css(".form-control")).click()
    await driver.findElement(By.css(".form-control")).sendKeys("pouet")
    await driver.findElement(By.css(".btn-outline-secondary")).click()
    {
      const value = await driver.findElement(By.css(".form-control")).getAttribute("value")
      assert(value == "pouet")
    }
  })
})
